version: '3.8'
services:
  postgres:
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kashmar552
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  # elasticsearch:
  #   image: elasticsearch:8.8.1
  #   container_name: elasticsearch
  #   volumes:
  #     - elasticsearch-data:/usr/share/elasticsearch/data
  #   ports:
  #     - 9200:9200
  #   environment:
  #     - ELASTIC_PASSWORD=kashmar552
  #     - discovery.type=single-node
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  # kibana:
  #   depends_on:
  #     - elasticsearch
  #   image: kibana:8.8.1
  #   container_name: kibana
  #   volumes:
  #     - kibana-data:/usr/share/kibana/data
  #   ports:
  #     - 5601:5601
  #   environment:
  #     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
volumes:
  postgres:
  # elasticsearch-data:
  # kibana-data:
